<?php
/**
 * #############################################################
 * ## Listen Live Plugin for FPP (fpp-ListenLive)             ##
 * ## Author: jessica12ryan                                   ##
 * ## URL: https://github.com/jessica12ryan/fpp-ListenLive    ##
 * #############################################################
 * ## footer.inc                                              ##
 * #############################################################
 */
?>
<div class="ll-footer mt-3 pt-2 text-muted small border-top" style="text-align:center;">
    Copyright &copy; 2026 jessica12ryan. Licensed under the MIT License.<br>FPP is &copy; Falcon Christmas. This plugin is an independent integration and is not affiliated with or endorsed by the Falcon Christmas project.
</div>
